#!/bin/bash

# ==============================================================================
# 脚本名称: deb_dns_cache_install.sh
# 描述: Debian 13 (Trixie) 一键全自动安装与配置 DNSmasq 双栈 (IPv4/IPv6) 缓存脚本
# ==============================================================================

# 设置颜色输出
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # 无颜色

echo -e "${GREEN}=== 开始执行 Debian 13 DNS 缓存一键安装脚本 (支持 IPv4/IPv6) ===${NC}"

# 1. 权限检查
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}错误: 请使用 root 用户或通过 sudo 运行此脚本！${NC}"
    exit 1
fi

# 2. 更新系统并安装所需软件包
echo -e "${YELLOW}[1/6] 正在更新软件包列表并安装 dnsmasq 与 dnsutils...${NC}"
apt update && apt install dnsmasq dnsutils -y
if [ $? -ne 0 ]; then
    echo -e "${RED}错误: 软件包安装失败，请检查网络连接或 APT 源。${NC}"
    exit 1
fi

# 3. 写入 dnsmasq 配置文件
echo -e "${YELLOW}[2/6] 正在配置 dnsmasq (同时开启 IPv4 与 IPv6 缓存)...${NC}"

# 备份原配置文件
if [ -f /etc/dnsmasq.conf ]; then
    mv /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
fi

cat > /etc/dnsmasq.conf << 'EOF'
# 1. 监听本地 IPv4 与 IPv6 环回地址
listen-address=127.0.0.1,::1
bind-interfaces

# 2. 优化缓存大小与性能
cache-size=4000
strict-order

# 3. 忽略系统默认 DNS，直接指定高效上游 DNS
no-resolv

# 上游 IPv4 DNS (Cloudflare / Google)
server=1.1.1.1
server=8.8.8.8

# 上游 IPv6 DNS (Cloudflare / Google)
server=2606:4700:4700::1111
server=2001:4860:4860::8888
EOF

# 4. 重启并激活服务
echo -e "${YELLOW}[3/6] 正在重启并设置 dnsmasq 开机自启...${NC}"
systemctl daemon-reload
systemctl restart dnsmasq
systemctl enable dnsmasq

# 5. 配置 /etc/resolv.conf 并加锁
echo -e "${YELLOW}[4/6] 正在配置系统 DNS 指向本地环回地址，并进行防写加锁...${NC}"

# 如果存在软链接或旧文件，先解除锁定并删除
if [ -f /etc/resolv.conf ]; then
    chattr -i /etc/resolv.conf 2>/dev/null
    rm -f /etc/resolv.conf
fi

# 创建新的静态 resolv.conf 文件
cat > /etc/resolv.conf << 'EOF'
# Generated by DNSmasq Auto Installer
nameserver 127.0.0.1
nameserver ::1
options timeout:1 attempts:1
EOF

# 使用 chattr +i 进行物理加锁，防止被 NetworkManager 或 DHCP 覆盖
chattr +i /etc/resolv.conf
if [ $? -eq 0 ]; then
    echo -e "${GREEN}成功: /etc/resolv.conf 已成功锁死保护。${NC}"
else
    echo -e "${YELLOW}警告: /etc/resolv.conf 加锁失败，请检查系统是否支持 chattr。${NC}"
fi

# 6. 自检与验证
echo -e "${YELLOW}[5/6] 正在进行本地 DNS 缓存自检...${NC}"
sleep 2

echo -e "${YELLOW}--- 第一次 IPv4 解析测试 (触发上游查询) ---${NC}"
dig @127.0.0.1 google.com +short
echo -e "${YELLOW}--- 第二次 IPv4 解析测试 (验证本地缓存) ---${NC}"
TIME_V4=$(dig @127.0.0.1 google.com | grep "Query time" | awk '{print $4}')
echo -e "${GREEN}IPv4 缓存解析耗时: ${TIME_V4} ms${NC}"

echo -e "${YELLOW}--- 第一次 IPv6 (AAAA) 解析测试 (触发上游查询) ---${NC}"
dig @::1 google.com AAAA +short
echo -e "${YELLOW}--- 第二次 IPv6 (AAAA) 解析测试 (验证本地缓存) ---${NC}"
TIME_V6=$(dig @::1 google.com AAAA | grep "Query time" | awk '{print $4}')
echo -e "${GREEN}IPv6 缓存解析耗时: ${TIME_V6} ms${NC}"

# 7. 安装完成提示
echo -e "\n${GREEN}=== [6/6] 全自动安装与配置完成！ ===${NC}"
echo -e "${GREEN}1. dnsmasq 服务状态:${NC} $(systemctl is-active dnsmasq)"
echo -e "${GREEN}2. /etc/resolv.conf 状态:${NC} $(lsattr /etc/resolv.conf | awk '{print $1}')"
echo -e "${YELLOW}提示: 如果后续需要手动修改 DNS，请先执行: sudo chattr -i /etc/resolv.conf${NC}"
